### PR TITLE
Add aurora port lock logic to SDM120C to share the same 485 adapter with aurora inverter

### PR DESCRIPTION
**Pull request by The-Drake**
With this "multi-merge" patch from aurora sources I'm now able to share the same port with aurora. sdm120c gently wait for the 485 port like aurora does. -w parameter is the same as aurora one.

I'm testing it now on my setup and it's quite stable.

Hope it helps. :)

### CODE REVIEW

**Comment by The-Drake** [comment]
Update: It seems that Aurora 1.8.8 needs a patch too, some more fix needed in previous pull request too: please wait.

Actually working in testing environment like a charm. :)

**Comment by The-Drake** [comment]
Last commit fixes locking logic. Working very well on my RPI.

**Comment by gianfrdp** [comment]
Thank you for your patch.
I will try to merge with my last commits

**Comment by The-Drake** [comment]
Grazie a te. :)

E' una patch importante, ma il risultato che mi ha dato è notevole. Sto
aspettando una risposta da Curt per la patch ad aurora che gli ho già
inviato.

Non ho capito invece le ultime modifiche che hai fatto per la gestione
degli errori. Secondo me ci sono un paio di punti che hanno dei problemi...

Bye,
Paolo.

On Tue, Aug 18, 2015 at 5:28 PM, gianfrdp <notifications@github.com> wrote:

> Thank you for your patch.
> I will try to merge with my last commits
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gianfrdp/SDM120C/pull/2#issuecomment-132250375>.
>



-- 
Bye,
   Paolo.

**Comment by gianfrdp** [comment]
Merged patch

**Pull request closed without merging**
